## Generated by Gemini - Not working locally but just to validate the bsfc map creation logic

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import griddata

zenon_df = pd.read_csv(
    "191011_Kennfeld_EA189_neu.xlsx - Zenon.csv",
    usecols=["Drehzahl Bremse", "Drehmoment Summe", "Spezifischer Verbrauch"],
)
zenon_df = zenon_df.drop(0)

x_series = pd.to_numeric(zenon_df["Drehzahl Bremse"], errors="coerce")
y_series = pd.to_numeric(zenon_df["Drehmoment Summe"], errors="coerce")
z_series = pd.to_numeric(zenon_df["Spezifischer Verbrauch"], errors="coerce")

df = pd.DataFrame({"x": x_series, "y": y_series, "z": z_series}).dropna()

x = df["x"].values
y = df["y"].values
z = df["z"].values

xi = np.linspace(x.min(), x.max(), 100)
yi = np.linspace(y.min(), y.max(), 100)
XI, YI = np.meshgrid(xi, yi)

ZI = griddata((x, y), z, (XI, YI), method="cubic")
if np.isnan(ZI).all():
    ZI = griddata((x, y), z, (XI, YI), method="linear")

plt.contourf(XI, YI, ZI, levels=20, cmap="viridis_r")
plt.colorbar(label="BSFC (g/kWh)")
plt.scatter(x, y, color="black", s=10, label="Messpunkte")

contour_lines = plt.contour(XI, YI, ZI, levels=10, colors="black", linewidths=0.5)
plt.clabel(contour_lines, inline=True, fontsize=8)

plt.xlabel("Motordrehzahl (U/min)")
plt.ylabel("Drehmoment (Nm)")
plt.title("BSFC Kennfeld (Brake Specific Fuel Consumption)")
plt.legend()
plt.tight_layout()
plt.savefig("bsfc_map.png", dpi=300)
plt.close()
